stages:
    - test

unit_tests:
    stage: test
    script:
        - ./bin/build-helper version
        - ./bin/build-helper test

pycodestyle:
    stage: test
    script:
        - pep8=$(command -v pycodestyle-3) && ln -s -f "${pep8}" /usr/bin/pycodestyle
        - ./bin/build-helper pycodestyle

shellcheck:
    stage: test
    script:
        - ./bin/build-helper shellcheck
